import pandas as pd

from investment_lab.util import check_is_true


class DynamicAllocationOverlay:
    @classmethod
    def apply_to_trades(
        cls,
        df_trades: pd.DataFrame,
        df_allocation: pd.DataFrame,
        lag_business_days: int = 1,
        allocation_col: str = "allocation",
        fill_value: float = 0.0,
    ) -> pd.DataFrame:
        """Apply a dynamic allocation overlay to an existing trade time series.

        Args:
            df_trades (pd.DataFrame): Daily trade time series generated by the strategy engine.
            df_allocation (pd.DataFrame): Daily allocation signal by date and ticker.
            lag_business_days (int): Number of business days between signal observation and trade application.
            allocation_col (str): Name of the allocation column.
            fill_value (float): Default allocation used when no signal is available.

        Returns:
            pd.DataFrame: Trade time series with dynamically scaled weights.
        """
        
        required_trade_cols = {"date", "entry_date", "option_id", "leg_name", "weight", "ticker"}
        required_alloc_cols = {"date", "ticker", allocation_col}

        missing_trade_cols = required_trade_cols.difference(df_trades.columns)
        missing_alloc_cols = required_alloc_cols.difference(df_allocation.columns)

        check_is_true(len(missing_trade_cols) == 0, f"df_trades is missing columns: {missing_trade_cols}")
        check_is_true(len(missing_alloc_cols) == 0, f"df_allocation is missing columns: {missing_alloc_cols}")
        check_is_true(lag_business_days >= 0, "lag_business_days must be >= 0.")

        df_alloc = df_allocation[["date", "ticker", allocation_col]].copy().sort_values(["ticker", "date"])
        df_alloc["entry_date"] = df_alloc["date"] + pd.offsets.BusinessDay(lag_business_days)
        df_alloc = df_alloc.drop(columns=["date"])

        df = df_trades.copy()
        df = df.merge(df_alloc, on=["entry_date", "ticker"], how="left")
        df[allocation_col] = df[allocation_col].fillna(fill_value)
        df["weight"] = df["weight"] * df[allocation_col]
        return df